import "./globals.css";

export const metadata = {
    title: "Trắc nghiệm",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {

    return (
        <html lang="en">
            <body>
                <main className="app">
                    {children}
                </main>
            </body>
        </html>
    );
}

